server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: microservicecloud-dept  #添加这个配置后，原来访问方式（zuulhost + 微服务名称）将不可用，只能用映射的方式（/mydept/）
  prefix: /nick
  ignored-services: "*"  #隐藏所有的真实微服务地址
  routes:
    mydept.serviceId: microservicecloud-dept  #隐藏真实的微服务名称，使用/mydept/**替代
    mydept.path: /mydept/**

info:
  app.name: nick-microcloud
  company.name: www.nick.com
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 1.0-SNAPSHOT

